config/routes.rb
Rails.application.routes.draw do
  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show", as: :page
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :destroy
  resources :relationships, only: [:create, :destroy, :index]
  resources :lessons, except: [:index, :destroy]
  resources :words, only: :index
  resources :activities, only: :index

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :categories do
      resources :words, only: :new 
    end 
    resources :words
    resources :users_data, only: :index
  end
end

app/models/supports/word.rb
class Supports::Word
  attr_reader :word

  def initialize word
    @word = word
  end

  def levels
    @levels ||= Word.levels
  end

  def categories
    @categories ||= Category.all.collect{|category| [category.name, category.id]}
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  scope :by_category_and_level, -> (id, count, level) {where(category_id: id, levels: level).limit count}
  
  has_many :answers, inverse_of: :word, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :lessons, through: :results

  validates :question, presence: true
  validate :check_answer_nil
  validate :must_have_two_answer
  validate :check_before_update, on: :update

  accepts_nested_attributes_for :answers,
    allow_destroy: true,
    reject_if: lambda {|attributes| attributes[:content].blank?}

  enum levels: [:easy, :normal, :hard]

  scope :filter_by_category, -> category_id{where category_id: 
    category_id if category_id.present?}
  scope :filter_by_level, -> level{where levels: level if level.present? }
  scope :all_word, -> user_id{}
  scope :learned, -> user_id{where(Settings.sql.word_learned, user_id)}
  scope :not_learned, -> user_id{where(Settings.sql.word_not_learned, user_id)}
  scope :alphabet, -> user_id{order(question: :desc)}
  scope :newest_update, -> user_id{order(updated_at: :desc)}

  def has_correct_answer?
    correct_answer = answers.is_correct
    correct_answer.size > 0 ? true : false
  end

  private

  def must_have_two_answer
    errors.add :answer, I18n.t("error.answer_size") if answers.size < 2
  end

  def check_answer_nil
    correct_answer = 
      answers.select{|answers|answers.is_correct? && !answers.marked_for_destruction?}
    errors.add :correct_answer,
      I18n.t("error.answer_nil") if correct_answer.empty?
    errors.add :correct_answer,
      I18n.t("error.answer_more_than_2") if correct_answer.size > 1
  end

  def check_before_update
    answers.each do |answer|
      if answer.is_correct? && answer.marked_for_destruction?
        errors.add :correct_answer, I18n.t("error.delete_true_answer")
      end
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :find_word, except: [:index, :new, :create]

  def index
    @words = if params[:option].present?
      Word.filter_by_category(params[:category_id])
        .filter_by_level(params[:levels]).send(params[:option], current_user)
    else
      Word.all
    end
    @words = @words.paginate page: params[:page],
      per_page: Settings.per_page_words
    @view_word = Supports::Word.new @words.first
  end

  def new
    @word = Word.new
    @view_word = Supports::Word.new @word
    Settings.number_of_answer.times {@word.answers.build}
    @category_id = params[:category_id]
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t "flash.word_created_success"
      redirect_to admin_words_path
    else
      @view_word = Supports::Word.new @word
      render :new
    end
  end

  def edit
    @view_word = Supports::Word.new @word
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "flash.word_updated_success"
      redirect_to admin_words_path
    else
      @view_word = Supports::Word.new @word
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t "flash.delete_word_success"
    else
      flash[:danger] = t "flash.delete_word_fail"
    end
    redirect_to admin_words_path
  end

  private
  def find_word
    @word= Word.find_by id: params[:id]
    unless @word
      flash[:danger] = t "flash.find_word_fail"
      redirect_to root_path
    end
  end

  def word_params
    params.require(:word).permit :category_id, :question, :levels,
      answers_attributes: [:id, :content, :is_correct, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @words = if params[:option].present?
      Word.filter_by_category(params[:category_id])
        .filter_by_level(params[:levels]).send(params[:option], current_user)
    else
      Word.all
    end
    @words = @words.paginate page: params[:page],
      per_page: Settings.per_page_words
    @view_word = Supports::Word.new @words.first
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/admin/words/_answer_fields.html.erb
<p class = "fields">
  <div class="row">
   <%= f.label :answer %><br/>
    <div class="col-md-6"><%= f.text_field :content %></div>
    <div class="col-md-3"><%= f.check_box :is_correct, class: "check_box" %></div>
    <div class="col-md-3"><%= f.hidden_field :_destroy %>
      <%= link_to t(".remove_answer"), "#", class: "remove_fields" %></div>
  </div>
</p>

app/views/admin/words/_filter_form.html.erb
<%= form_for admin_words_path, method: :get do |f| %>
  <div class="col-md-2">
    <%= select_tag :category_id, 
      options_for_select(@view_word.categories, params[:category_id]),
        include_blank: t(".all_category"), class: "form-control" %>
  </div>
  <div class="col-md-2">
    <%= select_tag :levels,
      options_for_select(@view_word.levels, params[:levels]),
      include_blank: t(".all_level"),class: "form-control" %>
  </div>
  <% Settings.word_status.each do |key,value| %>
    <div class="col-md-2">
      <div class="radio">
        <%= radio_button_tag :option, value,
          checked = (params[:option] == value || params[:option].blank?) %>
        <div class="radio_fix"><%= value %></div>
      </div>
    </div>
  <% end %>
  <div class="col-md-2">
    <%= f.submit t(".filter"), class: "btn btn-info" %>
  </div>
<% end %>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :question %>
  <%= f.text_field :question, class: "form-control" %>
  <% if @category_id.present? || @word.category_id.present? %>
    <%= f.hidden_field :category_id, value: @category_id  || @word.category_id %>
  <% else %>
    <%= f.label :category_id %>
    <%= f.select :category_id, @view_word.categories, {}, class: "form-control" %>
  <% end %>
  <%= f.label :levels %>  
  <%= f.select :levels, options_for_select(
    @view_word.levels.collect {|l| l[0]}, @word.levels), {}, class: "form-control" %>
  <div id ="answer_field">
    <%= f.fields_for :answers do |builder| %>
      <%= render "answer_fields", f: builder %>
    <% end %>
    <%= link_to_add_fields t(".more_answer"), f, :answers %>
  </div>
  <%= f.hidden_field :number_answer, value: @word.answers.size, 
    class: "number_answer" %>
  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/words/_word.html.erb
<li>
  <div class="col-md-2">
    <%= link_to word.question, "#" %>
  </div>
  <div class="col-md-4">
    <%= t ".created_at" %> : <%=  word.created_at.strftime t ".time_default" %>
  </div>
  <div class="col-md-2">
    <%= word.levels %>
  </div>
  <div class="col-md-2">
    <%= link_to t(".delete"), admin_word_path(word),
      class: "btn btn-xs btn-danger",method: :delete,
      data: {confirm: t(".ask_before_delete")} %>
  </div>
  <div class="col-md-2">
    <%= link_to t(".update"), edit_admin_word_path(word),
      class: "btn btn-xs btn-warning" %>
  </div>
</li>

app/views/admin/words/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t(".title") %>
<div align="center">
  <%= link_to t(".add_new_word"), new_admin_word_path,
    class: "btn btn-primary" %>
</div>
<div class="row" id="filter_word_form">
  <form class="form-inline">
    <%= render "filter_form" %>
  </form>
</div>
<ul class="users">
  <% @words.each do |word| %>
    <li>
      <%= render word %>
    </li>
  <% end %>
</ul>
<%= will_paginate @words %>

app/views/admin/words/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>