config/routes.rb
Rails.application.routes.draw do
  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show", as: :page
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :destroy
  resources :relationships, only: [:create, :destroy, :index]
  resources :lessons, except: [:index, :destroy]
  resources :words, only: :index
  resources :activities, only: :index

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :categories do
      resources :words, only: :new 
    end 
    resources :words
    resources :users_data, only: :index
  end
end

app/views/shared/_button_action.html.erb
<div class="col-md-4 col-md-offset-4" >
  <div class="row">
      <%= link_to t("users.show.link_my_lesson"), user, class: "btn btn-primary"%>
      <%= link_to t("users.show.link_word_list"), words_path, class: "btn btn-primary"%>
      <%= link_to t("users.show.link_do_lesson"), new_lesson_path, class: "btn btn-primary"%>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, 
        t("flash.error")) %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_filter_form.html.erb
<%= form_for words_path, method: :get, remote: true do |f| %>
  <div class="col-md-2">
    <%= select_tag :category_id, 
      options_for_select(@view_word.categories, params[:category_id]),
        include_blank: t(".all_category"), class: "form-control" %>
  </div>
  <div class="col-md-2">
    <%= select_tag :levels,
      options_from_collection_for_select(@view_word.levels, :last, :first, 
        params[:levels]),
      include_blank: t(".all_level"),class: "form-control" %>
  </div>
  <% Settings.status.each do |key,value| %>
    <div class="col-md-2">
      <div class="radio">
        <%= radio_button_tag :option, value,
          checked = (params[:option] == value || params[:option].blank?) %>
        <div class="radio_fix"><%= value %></div>
      </div>
    </div>
  <% end %>
  <div class="col-md-2">
    <%= f.submit t(".filter"), class: "btn btn-info" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to relationships_path user_id: current_user, relationship: "following" do %>
    <strong id="following" class="stat">
      <%= current_user.following.count %>
    </strong>
    following
  <% end %>
  <%= link_to relationships_path user_id: current_user, relationship: "followers" do %>
    <strong id="followers" class="stat">
      <%= current_user.followers.count %>
    </strong>
    followers
  <% end %>
</div>