config/routes.rb
Rails.application.routes.draw do
  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show", as: :page
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :destroy
  resources :relationships, only: [:create, :destroy, :index]
  resources :lessons, except: [:index, :destroy]
  resources :words, only: :index
  resources :activities, only: :index

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :categories do
      resources :words, only: :new 
    end 
    resources :words
    resources :users_data, only: :index
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :find_category, except: [:index, :new, :create]

  def index
    @categories = Category.paginate page: params[:page],
      per_page: Settings.per_page_categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "flash.category_created"
      redirect_to admin_categories_path
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "flash.create_category_success"
    else
      flash[:danger] = t "flash.delete_category_fail"
    end
    redirect_to admin_categories_path
  end

  def show
    @words = @category.words .paginate page: params[:page],
      per_page: Settings.per_page_words
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "flash.category_updated_success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  private
  def find_category
    @category= Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "flash.find_category_fail"
      redirect_to root_path
    end
  end

  def category_params
    params.require(:category).permit :name, :duration, :question_count
  end
end

app/views/admin/categories/_category.html.erb
<li>
  <div class="col-md-2">
    <%= link_to category.name, admin_category_path(category) %>
  </div>
  <div class="col-md-2">
    <%= t ".duration" %><%= t ".time", duration: category.duration %>
  </div>
  <div class="col-md-2">
    <%= t ".number_question" %><%= category.question_count %>
  </div>
  <div class="col-md-4">
    <%= t ".created_at" %><%= l category.created_at, format: :long %>
  </div>
  <div class="col-md-2">
    <%= link_to t(".update"), edit_admin_category_path(category),
      class: "btn btn-xs btn-warning" %>
  </div>
</li>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :duration %>
  <%= f.select :duration, options_for_select(Settings.duration, 
    @category.duration), {}, class: "form-control" %>
  <%= f.label :number_question %>
  <%= f.select :question_count, options_for_select(
    Settings.question_count, @category.question_count), 
    {}, class: "form-control" %>
  <%= f.submit t(".new_category"), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t(".title") %>
<div align="center">
  <%= link_to t(".add_new_category"), new_admin_category_path,
    class: "btn btn-primary" %>
</div>
<ul class="users">
  <% @categories.each do |category| %>
    <li>
      <%= render category %>
    </li>
  <% end %>
</ul>
<%= will_paginate @categories %>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<h1><%= @category.name %></h1>
<div class="row">
  <div class="col-md-6">
    <%= link_to t(".add_new_word") + @category.name, 
      new_admin_category_word_path(@category.id), class: "btn btn-primary" %>
  </div>
  <div class="col-md-6" align="right">
    <%= link_to t(".delete"), admin_category_path(@category.id),
      class: "btn btn-danger",method: :delete,
      data: {confirm: t(".ask_before_delete")} %>
  </div>
</div>
<ul class="users">
  <% @words.each do |word| %>
    <li>
      <%= render word %>
    </li>
  <% end %>
</ul>
<%= will_paginate @words %>