config/routes.rb
Rails.application.routes.draw do
  root "static_pages#show", page: "home"
  get "/pages/:page" => "static_pages#show", as: :page
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :destroy
  resources :relationships, only: [:create, :destroy, :index]
  resources :lessons, except: [:index, :destroy]
  resources :words, only: :index
  resources :activities, only: :index

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :categories do
      resources :words, only: :new 
    end 
    resources :words
    resources :users_data, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activities, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :downcase_email
  before_create :create_activation_digest
  
  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}

  has_secure_password

  scope :find_by_username, -> name{where Settings.sql.find_user, "%#{name}%"}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def to_csv
      CSV.generate do |csv|
        csv << column_names
        all.each do |user|
          csv << user.attributes.values_at(*column_names)
        end
      end
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def current_user? user
    self == user
  end

  def activate
    update_attributes activated: true, activated_at: Time.zone.now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attributes reset_digest: User.digest(reset_token),
      reset_sent_at: Time.zone.now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  private
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :find_user, only: [:show, :destroy]

  def index
    @users = if params[:name].present?
      User.find_by_username params[:name]
    else
      User.all
    end
    @users = @users.paginate page: params[:page],
      per_page: Settings.per_page_users
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def destroy
    if @user.destroy
      flash[:success] = t "flash.delete_user_success"
    else
      flash[:danger] = t "flash.delete_user_fail"
    end
    redirect_to admin_users_path
  end

  private
  def find_user
    @user= User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "flash.find_user_fail"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:create, :new]
  before_action :change_to_admin, only: [:show]
  before_action :find_user, except: [:index, :new, :create]
  before_action :valid_user, only: [:edit, :update]

  def index
    @users = if params[:name].present?
      User.find_by_username params[:name]
    else
      User.all
    end
    @users = @users.paginate page: params[:page],
      per_page: Settings.per_page_users
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @lessons = current_user.lessons.desc.paginate page: params[:page],
      per_page: Settings.users_show_lessons
    @relationship = if current_user.following? @user
      current_user.active_relationships.find_by followed_id: @user.id
    else
      current_user.active_relationships.build
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "flash.login_success"
      redirect_back_or @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "users.profile_updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  private
  def find_user
    @user= User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "flash.find_user_fail"
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit :name, :email, :password, :avatar,
      :password_confirmation 
  end

  def valid_user
    redirect_to root_url unless @user == current_user
  end

  def change_to_admin
    redirect_to admin_users_path if current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_all_user.html.erb
<ul class="users">
  <%= render @users %>
  <%= will_paginate @users %>
</ul>

app/views/admin/users/_search_user.html.erb
<%= form_for admin_words_path, method: :get, remote: true do |f| %>
  <div class="col-md-4">
    <%= text_field_tag :name, params[:name],class: "form-control", 
      placeholder: t(".username") %>
  </div>
  
  <div class="col-md-1">
    <%= f.submit t(".find"), class: "btn btn-info" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.size %>
  <div class="col-md-2">
    <%= link_to user.name, admin_user_path(user) %>
  </div>
  <div class="col-md-4">
    <%= t ".created_at" %> : <%= l user.created_at, format: :long %>
  </div>
  <% unless user.admin? %>
    <div class="col-md-2">
      <%= link_to t(".delete"), admin_user_path(user.id),
        class: "btn btn-xs btn-danger",method: :delete,
        data: {confirm: t(".ask_before_delete")} %>
    </div>
  <% end %>
</li>

app/views/admin/users/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <%= render "search_user" %>
</div>
<div class="show_user" >
  <%= render "all_user" %>
</div>
<div class="row">
  <div class="col-md-6" align="right">
    <%= link_to t(".export_csv"), 
      admin_users_data_path(format: Settings.file_format.csv) %>
  </div>
  <div class="col-md-5" >
    <%= link_to t(".export_execl"), 
      admin_users_data_path(format: Settings.file_format.xls) %>
  </div>
</div>

app/views/admin/users/index.js.erb
$('.show_user').html("<%= j render 'all_user' %>");

app/views/admin/users/show.html.erb
<% provide :title, @user.name %>
<h1><%= t ".title" %></h1><hr>
<div class="row">
  <div class="col-md-4">
    <div class="profile_label"><%= t ".full_name" %></div>
  </div>
  <div class="col-md-6">
    <%= text_field_tag :fullname, @user.name, 
      class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="profile_label"><%= t ".email" %></div>
  </div>
  <div class="col-md-6">
    <%= text_field_tag :emal, @user.email, 
      class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="profile_label"><%= t ".created_at" %></div>
  </div>
  <div class="col-md-6">
    <%= text_field_tag :created_at, 
      @user.created_at.strftime(t ".time_default"), 
      class: "form-control" %>
  </div>
</div>
<div class="row">
  <%= link_to t(".return"), admin_users_path %>
</div> 